---
  - name: squid3.5のrepoファイルを転送
    copy:
      src: /var/lib/jenkins/middle/squid-3.5.16-1.el6.x86_64.rpm
      dest: /tmp/squid-3.5.16-1.el6.x86_64.rpm

  - name: インストール開始
    yum:
      name: /tmp/squid-3.5.16-1.el6.x86_64.rpm
      state: latest

  - name: squid.conf 置き換え
    copy:
      src: squid.conf
      dest: /etc/squid/squid.conf

  - name: squidを再起動
    service:
      name: squid
      state: restarted
      enabled: yes
