---
  - name: apache をインストール
    yum:
      name: httpd
      state: latest

  - name: ドキュメントルート作成
    file:
      path: /www
      state: directory
      owner: apache
      mode: 0777

  - name: httpd.conf を置き換え
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/httpd.conf

  - name: index.html をドキュメントルートへ配置
    copy:
      src: index.html
      dest: /www/index.html
      owner: apache
      mode: 0777

  - name: apache再起動
    systemd:
      name: httpd
      enabled: yes
      state: restarted
