---
  - name: yumでsquidをインストール
    yum:
      name: squid
      state: latest

  - name: squid.confを配置する
    copy:
      src: squid.conf
      dest: /etc/squid/squid.conf

  - name: squidを再起動
    systemd:
      name: squid
      enabled: yes
      state: restarted
