---
  - name: Apache2.4のrepoファイルを転送
    copy:
      src: /var/lib/jenkins/middle/epel-httpd24.repo
      dest: /etc/yum.repos.d/epel-httpd24.repo

  - name: インストール開始
    yum:
      name: "{{ packages }}" 
      state: latest
    vars:
      packages:
        - httpd24-httpd
        - httpd24-httpd-devel

  - name: ドキュメントルートフォルダを作成
    file:
      path: /www
      state: directory
      mode: 0777

  - name: デフォルトindex.htmlを配置
    copy:
      src: index.html
      dest: /www/index.html
      mode: 0777

  - name: httpd.conf 置き換え
    copy:
      src: httpd.conf
      dest: /opt/rh/httpd24/root/etc/httpd/conf/httpd.conf

  - name: 80番ポート占領プロセス停止
    shell: fuser -k -n tcp 80

  - name: apacheを再起動
    service:
      name: httpd24-httpd
      state: restarted
      enabled: yes
